// Generated by ReScript, PLEASE EDIT WITH CARE


function sum(a) {
  return a.reduce((function (p, c) {
                return p + c | 0;
              }), 0);
}

function make(t) {
  return sum(t.map(sum).sort(function (a, b) {
                    return b - a | 0;
                  }).slice(0, 3));
}

var $$Array;

export {
  $$Array ,
  sum ,
  make ,
}
/* No side effect */
