// Generated by ReScript, PLEASE EDIT WITH CARE


function max(prim0, prim1) {
  return Math.max(prim0, prim1);
}

function make(t) {
  return t.reduce((function (prev, list) {
                return Math.max(prev, list.reduce((function (p, c) {
                                  return p + c | 0;
                                }), 0));
              }), 0);
}

var $$Array;

export {
  $$Array ,
  max ,
  make ,
}
/* No side effect */
