// Generated by ReScript, PLEASE EDIT WITH CARE

import * as ReScriptHash from "rescript-hash/src/ReScriptHash.mjs";

function make(s) {
  var i = 0;
  var v;
  var $$break = false;
  while(!$$break) {
    if (i === 10000000) {
      $$break = true;
    } else {
      var hash = ReScriptHash.MD5.makeU(s + String(i));
      if (hash.startsWith("000000")) {
        v = i;
        $$break = true;
      } else {
        i = i + 1 | 0;
      }
    }
  };
  return v;
}

var $$String$1;

var Int;

var MD5;

var limit = 10000000;

export {
  $$String$1 as $$String,
  Int ,
  MD5 ,
  limit ,
  make ,
}
/* No side effect */
