// Generated by ReScript, PLEASE EDIT WITH CARE

import * as AOC2015_04_part1 from "../part1/AOC2015_04_part1.mjs";

function make(s) {
  return AOC2015_04_part1.hack("000000", 10000000, s);
}

var $$String;

var Int;

var MD5;

export {
  $$String ,
  Int ,
  MD5 ,
  make ,
}
/* No side effect */
