// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as AOC2022_03 from "../AOC2022_03.mjs";
import * as Pervasives from "rescript/lib/es6/pervasives.js";
import * as Belt_MutableSetInt from "rescript/lib/es6/belt_MutableSetInt.js";

function reduce(prim0, prim1, prim2) {
  return prim0.reduce(Curry.__2(prim1), prim2);
}

function toSet(s) {
  return Belt_MutableSetInt.fromArray(reduce(Array.from(s), (function (p, c) {
                    var n = c.codePointAt(0);
                    if (n !== undefined) {
                      p.push(n);
                      return p;
                    } else {
                      return p;
                    }
                  }), []));
}

function getPriority(s0, s1, s2) {
  var match = Belt_MutableSetInt.toArray(Belt_MutableSetInt.intersect(Belt_MutableSetInt.intersect(toSet(s0), toSet(s1)), toSet(s2)));
  return AOC2022_03.CodePoint.make(match.length !== 1 ? Pervasives.failwith("no intersection") : match[0]);
}

function make(a) {
  return reduce(a, (function (p, param) {
                return p + getPriority(param[0], param[1], param[2]) | 0;
              }), 0);
}

export {
  make ,
}
/* No side effect */
