// Generated by ReScript, PLEASE EDIT WITH CARE


function make(l, w, h) {
  return Math.imul(Math.imul(l, w), h) + ((
            l > w ? (
                l > h ? w + h | 0 : w + l | 0
              ) : (
                w > h ? h + l | 0 : w + l | 0
              )
          ) << 1) | 0;
}

export {
  make ,
}
/* No side effect */
