// Generated by ReScript, PLEASE EDIT WITH CARE


function max(prim0, prim1) {
  return Math.max(prim0, prim1);
}

function min(prim0, prim1) {
  return Math.min(prim0, prim1);
}

function make(l, w, h) {
  return Math.imul(Math.imul(l, w), h) + ((((l + w | 0) + h | 0) - Math.max(l, Math.max(w, h)) | 0) << 1) | 0;
}

export {
  max ,
  min ,
  make ,
}
/* No side effect */
