// Generated by ReScript, PLEASE EDIT WITH CARE


function make(s) {
  if (s.length > 3 && /(.)[^\1]\1/g.test(s)) {
    return /(.)([^\1])(?:.*\1\2)/g.test(s);
  } else {
    return false;
  }
}

var Re;

var $$String;

export {
  Re ,
  $$String ,
  make ,
}
/* No side effect */
