// Generated by ReScript, PLEASE EDIT WITH CARE

import * as AOC2022_03 from "../AOC2022_03.mjs";
import * as Pervasives from "rescript/lib/es6/pervasives.js";
import * as Belt_MutableSetInt from "rescript/lib/es6/belt_MutableSetInt.js";

function getPriority(s) {
  var i = 0;
  var r;
  var mid = s.length / 2 | 0;
  var $$break = false;
  var s0 = Belt_MutableSetInt.make(undefined);
  var s1 = Belt_MutableSetInt.make(undefined);
  while(!$$break) {
    var match = s[i].codePointAt(0);
    var match$1 = s[i + mid | 0].codePointAt(0);
    if (match !== undefined && match$1 !== undefined) {
      if (match === match$1 || Belt_MutableSetInt.has(s0, match$1)) {
        r = match$1;
        $$break = true;
      } else if (Belt_MutableSetInt.has(s1, match)) {
        r = match;
        $$break = true;
      } else {
        Belt_MutableSetInt.add(s0, match);
        Belt_MutableSetInt.add(s1, match$1);
        if ((i + 1 | 0) === mid) {
          $$break = true;
        } else {
          i = i + 1 | 0;
        }
      }
    } else {
      $$break = true;
    }
  };
  var r$1 = r;
  var tmp;
  if (r$1 !== undefined) {
    tmp = r$1;
  } else {
    var match$2 = Belt_MutableSetInt.toArray(Belt_MutableSetInt.intersect(s0, s1));
    tmp = match$2.length !== 1 ? Pervasives.failwith("no intersection") : match$2[0];
  }
  return AOC2022_03.CodePoint.make(tmp);
}

function make(a) {
  return a.reduce((function (p, c) {
                return p + getPriority(c) | 0;
              }), 0);
}

export {
  make ,
}
/* No side effect */
