// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Pervasives from "rescript/lib/es6/pervasives.js";
import * as AOC2022_02_part1 from "../part1/AOC2022_02_part1.mjs";

function calculateMove(s1, s2) {
  switch (s2) {
    case "X" :
        var match = AOC2022_02_part1.Game.toState(s1);
        var tmp;
        switch (match) {
          case /* Rock */0 :
              tmp = /* Scissors */2;
              break;
          case /* Paper */1 :
              tmp = /* Rock */0;
              break;
          case /* Scissors */2 :
              tmp = /* Paper */1;
              break;
          
        }
        return {
                TAG: /* Loss */2,
                _0: tmp
              };
    case "Y" :
        return {
                TAG: /* Draw */1,
                _0: AOC2022_02_part1.Game.toState(s1)
              };
    case "Z" :
        var match$1 = AOC2022_02_part1.Game.toState(s1);
        var tmp$1;
        switch (match$1) {
          case /* Rock */0 :
              tmp$1 = /* Paper */1;
              break;
          case /* Paper */1 :
              tmp$1 = /* Scissors */2;
              break;
          case /* Scissors */2 :
              tmp$1 = /* Rock */0;
              break;
          
        }
        return {
                TAG: /* Win */0,
                _0: tmp$1
              };
    default:
      return Pervasives.failwith("incorrect value");
  }
}

function make(s1, s2) {
  return AOC2022_02_part1.Game.outcome(calculateMove(s1, s2));
}

var Game = {
  calculateMove: calculateMove,
  make: make
};

function make$1(t) {
  return t.reduce((function (prev, param) {
                return prev + make(param[0], param[1]) | 0;
              }), 0);
}

var $$Array;

export {
  $$Array ,
  Game ,
  make$1 as make,
}
/* No side effect */
