// Generated by ReScript, PLEASE EDIT WITH CARE

import * as AOC2022_06 from "../AOC2022_06.mjs";

function make(param) {
  return AOC2022_06.make(14, param);
}

export { make };
/* No side effect */
