// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Id from "rescript/lib/es6/belt_Id.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as Belt_MutableMap from "rescript/lib/es6/belt_MutableMap.js";
import * as Belt_MutableSetInt from "rescript/lib/es6/belt_MutableSetInt.js";

function cmp(a, b) {
  return a - b | 0;
}

var M = Belt_Id.MakeComparable({
      cmp: cmp
    });

function make(s) {
  var counter = 0;
  var cursor = [
    0,
    0
  ];
  var path = Belt_MutableMap.make(M);
  for(var i = 0 ,i_finish = s.length; i < i_finish; ++i){
    var match = cursor;
    var y = match[1];
    var x = match[0];
    var match$1 = s[i];
    var tmp;
    switch (match$1) {
      case "<" :
          tmp = [
            x - 1 | 0,
            y
          ];
          break;
      case ">" :
          tmp = [
            x + 1 | 0,
            y
          ];
          break;
      case "^" :
          tmp = [
            x,
            y + 1 | 0
          ];
          break;
      case "v" :
          tmp = [
            x,
            y - 1 | 0
          ];
          break;
      default:
        tmp = [
          x,
          y
        ];
    }
    cursor = tmp;
    var match$2 = cursor;
    var y$1 = match$2[1];
    var x$1 = match$2[0];
    var v = Belt_MutableMap.get(path, x$1);
    if (v !== undefined) {
      var v$1 = Caml_option.valFromOption(v);
      if (Belt_MutableSetInt.has(v$1, y$1)) {
        counter = counter + 1 | 0;
      } else {
        Belt_MutableSetInt.add(v$1, y$1);
      }
    } else {
      Belt_MutableMap.set(path, x$1, Belt_MutableSetInt.fromArray([y$1]));
    }
  }
  return s.length - counter | 0;
}

var $$String;

var $$Map;

var SetInt;

export {
  $$String ,
  $$Map ,
  SetInt ,
  M ,
  make ,
}
/* M Not a pure module */
