// Generated by ReScript, PLEASE EDIT WITH CARE


function make(s) {
  var v = 0;
  for(var i = 0 ,i_finish = s.length; i < i_finish; ++i){
    var match = s[i];
    var tmp;
    switch (match) {
      case "(" :
          tmp = 1;
          break;
      case ")" :
          tmp = -1;
          break;
      default:
        tmp = 0;
    }
    v = v + tmp | 0;
  }
  return v;
}

var $$String;

export {
  $$String ,
  make ,
}
/* No side effect */
