// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Caml_obj from "rescript/lib/es6/caml_obj.js";

function isInRange(param, param$1) {
  var e2 = param$1[1];
  var s2 = param$1[0];
  var e1 = param[1];
  var s1 = param[0];
  if (Caml_obj.lessequal(s1, s2) && Caml_obj.lessequal(e2, e1)) {
    return true;
  } else if (Caml_obj.greaterequal(s1, s2)) {
    return Caml_obj.greaterequal(e2, e1);
  } else {
    return false;
  }
}

function make(a) {
  return a.reduce((function (p, param) {
                if (isInRange(param[0], param[1])) {
                  return p + 1 | 0;
                } else {
                  return p;
                }
              }), 0);
}

export {
  make ,
}
/* No side effect */
