// Generated by ReScript, PLEASE EDIT WITH CARE

import * as ReScriptHash from "rescript-hash/src/ReScriptHash.mjs";

function hack(substring, limit, s) {
  var i = 0;
  var v;
  var $$break = false;
  while(!$$break) {
    if (i === limit) {
      $$break = true;
    } else {
      var hash = ReScriptHash.MD5.makeU(s + String(i));
      if (hash.startsWith(substring)) {
        v = i;
        $$break = true;
      } else {
        i = i + 1 | 0;
      }
    }
  };
  return v;
}

function make(s) {
  return hack("00000", 10000000, s);
}

var $$String$1;

var Int;

var MD5;

export {
  $$String$1 as $$String,
  Int ,
  MD5 ,
  hack ,
  make ,
}
/* No side effect */
