// Generated by ReScript, PLEASE EDIT WITH CARE


function make(s) {
  if (!/^((?!ab|cd|pq|xy).)*$/g.test(s)) {
    return false;
  }
  var matches = s.match(/[aeiou]/g);
  if (matches !== null && matches.length >= 3) {
    return /(.)\1/g.test(s);
  } else {
    return false;
  }
}

var $$Array;

var Re;

var $$String;

export {
  $$Array ,
  Re ,
  $$String ,
  make ,
}
/* No side effect */
