// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Pervasives from "rescript/lib/es6/pervasives.js";
import * as Belt_MutableMapString from "rescript/lib/es6/belt_MutableMapString.js";

function make(size, s) {
  var i = 0;
  var max = s.length;
  var $$break = false;
  var map = Belt_MutableMapString.make(undefined);
  while (!$$break) {
    if (((i + 1) | 0) === max || Belt_MutableMapString.size(map) === size) {
      $$break = true;
    } else {
      var letter = s[i];
      if (Belt_MutableMapString.has(map, letter)) {
        var v = Belt_MutableMapString.get(map, letter);
        if (v !== undefined) {
          Belt_MutableMapString.clear(map);
          i = (v + 1) | 0;
        } else {
          Pervasives.failwith("");
        }
      } else {
        Belt_MutableMapString.set(map, letter, i);
        i = (i + 1) | 0;
      }
    }
  }
  return i;
}

export { make };
/* No side effect */
