// Generated by ReScript, PLEASE EDIT WITH CARE


function min(prim0, prim1) {
  return Math.min(prim0, prim1);
}

function make(l, w, h) {
  var a = Math.imul(l, w);
  var b = Math.imul(l, h);
  var c = Math.imul(w, h);
  var min = Math.min(Math.min(a, b), c);
  return (((a + b | 0) + c | 0) << 1) + min | 0;
}

export {
  min ,
  make ,
}
/* No side effect */
